/* The Orazaka demo page (/products/orazaka/demos): structure only — the words are in messages
   (site.orazakaDemo). Clips are recordings of the real web client signed in as Eric, the demo persona
   (`orazaka demo seed`, orazaka-cli; `npm run record:tour`, orazaka-web-client), stored as
   public/assets/orazaka/tour/<id>.{webm,mp4,jpg}. Visuals were generated by Orazaka's own image Studio on one Mac
   (Stable Diffusion 1.5 through stable-diffusion.cpp on Metal), one job at a time: public/assets/orazaka/made-here/<id>.webp. */

/** The whole tour, in the order Eric's day runs. */
export const DEMO_TOUR = ["dashboard", "chat", "create", "studios", "packs", "settings"] as const;
export type DemoClipId = (typeof DEMO_TOUR)[number];

/** One section per thing a client wants done; each plays the clip that shows it. */
export const DEMO_USE_CASES = [
  { id: "documents", clip: "chat", icon: "knowledge" },
  { id: "visuals", clip: "create", icon: "image" },
  { id: "studios", clip: "studios", icon: "studio" },
  { id: "costs", clip: "packs", icon: "credits" },
] as const satisfies readonly { id: string; clip: DemoClipId; icon: string }[];

/**
 * Images Orazaka generated on the Mac, with the exact prompt that was sent (a record, so it stays in the language it
 * was typed in). Their description and use are messages: site.orazakaDemo.gallery.items.<id>.
 */
export const DEMO_GALLERY = [
  {
    id: "lamp",
    prompt:
      "Product photo of a sculpted ceramic table lamp glowing warm orange on a dark slate plinth, deep ink-blue background, soft rim light, minimal studio, high detail",
  },
  {
    id: "coffee",
    prompt:
      "Top-down flat lay of a matte coffee bag and a ceramic cup on dark navy linen, warm orange accents, soft window light, product catalogue photo, high detail",
  },
  {
    id: "serum",
    prompt: "Minimal skincare dropper bottle in amber glass on a wet black stone, orange backlight, dark background, luxury cosmetics advertisement photo",
  },
  {
    id: "interior",
    prompt: "Modern living room corner with a sculptural orange armchair and a ceramic floor lamp at dusk, dark blue walls, interior design catalogue photo",
  },
  {
    id: "scarf",
    prompt: "Folded knitted orange wool scarf on dark charcoal felt, soft studio light, empty space on the left, winter campaign banner photo",
  },
  {
    id: "giftbox",
    prompt: "Plain kraft gift box tied with an orange ribbon on a dark walnut table, moody product photography, shallow depth of field",
  },
  {
    id: "glass",
    prompt: "Abstract 3D render of glowing orange glass shapes floating over a deep ink-blue background, soft reflections, premium brand visual",
  },
  {
    id: "sneaker",
    prompt: "Plain white minimalist sneaker without logo on an orange pedestal, dark navy background, studio product photography, crisp shadows",
  },
] as const;
export type DemoGalleryId = (typeof DEMO_GALLERY)[number]["id"];

export const tourSrc = (id: DemoClipId) => `/assets/orazaka/tour/${id}`;
export const gallerySrc = (id: DemoGalleryId) => `/assets/orazaka/made-here/${id}.webp`;
