/* GENERATED by scripts/gen-ui-docs.mjs from @krizaka/ui@2.0.0-beta.3/registry — do not edit.
   One live demo per primitive (client modules of the package), loaded by ComponentPreview. */

export const UI_DEMOS = {
  "alert": () => import("@krizaka/ui/registry/demos/alert"),
  "avatar": () => import("@krizaka/ui/registry/demos/avatar"),
  "badge": () => import("@krizaka/ui/registry/demos/badge"),
  "button": () => import("@krizaka/ui/registry/demos/button"),
  "card": () => import("@krizaka/ui/registry/demos/card"),
  "checkbox": () => import("@krizaka/ui/registry/demos/checkbox"),
  "chip": () => import("@krizaka/ui/registry/demos/chip"),
  "cn": () => import("@krizaka/ui/registry/demos/cn"),
  "command": () => import("@krizaka/ui/registry/demos/command"),
  "confirm-button": () => import("@krizaka/ui/registry/demos/confirm-button"),
  "countdown": () => import("@krizaka/ui/registry/demos/countdown"),
  "dialog": () => import("@krizaka/ui/registry/demos/dialog"),
  "dropdown-menu": () => import("@krizaka/ui/registry/demos/dropdown-menu"),
  "empty-state": () => import("@krizaka/ui/registry/demos/empty-state"),
  "field": () => import("@krizaka/ui/registry/demos/field"),
  "kbd": () => import("@krizaka/ui/registry/demos/kbd"),
  "page-header": () => import("@krizaka/ui/registry/demos/page-header"),
  "popover": () => import("@krizaka/ui/registry/demos/popover"),
  "progress": () => import("@krizaka/ui/registry/demos/progress"),
  "radio-group": () => import("@krizaka/ui/registry/demos/radio-group"),
  "separator": () => import("@krizaka/ui/registry/demos/separator"),
  "skeleton": () => import("@krizaka/ui/registry/demos/skeleton"),
  "slider": () => import("@krizaka/ui/registry/demos/slider"),
  "slot": () => import("@krizaka/ui/registry/demos/slot"),
  "spinner": () => import("@krizaka/ui/registry/demos/spinner"),
  "stat": () => import("@krizaka/ui/registry/demos/stat"),
  "switch": () => import("@krizaka/ui/registry/demos/switch"),
  "tabs": () => import("@krizaka/ui/registry/demos/tabs"),
  "theme": () => import("@krizaka/ui/registry/demos/theme"),
  "toast": () => import("@krizaka/ui/registry/demos/toast"),
  "tooltip": () => import("@krizaka/ui/registry/demos/tooltip"),
} as const;

export type UiDemoName = keyof typeof UI_DEMOS;

export const UI_REGISTRY_VERSION = "2.0.0-beta.3";
