#!/usr/bin/env node
/* /docs/ui is generated from the @krizaka/ui registry (the installed package) at every build — the code of each
   component drives its page: meta.ts (summary, when to use, accessibility, platforms), its named examples and its
   props. Nothing about a component is written here.

   This script writes what a bundler and a static host need (git-ignored, rewritten by `postinstall`, `dev` and
   `build`; the pages themselves are virtual: lib/docs-source.ts reads the registry):
   - lib/ui-examples.ts      the import map of the live web examples;
   - public/ui-examples/     the screenshots of the React Native examples (dark and light: the Linux baselines of
                             their stories, shipped in the package), which have no live preview on the web.
   and checks that the registry is complete enough to render: every component has its title, summary, platforms and
   at least one example per platform, every example's compiled module is in the package, every related component
   exists, and every optional enrichment page (content/docs/ui/components/<name>.mdx) is a component of the registry.

   Usage: node scripts/gen-ui-docs.mjs [--strict | --check]
     (none)     writes lib/ui-examples.ts; reports an incomplete registry without failing (`postinstall`, `dev`).
     --strict   writes it and exits 1 when the registry is incomplete (`npm run build`).
     --check    writes nothing; exits 1 when lib/ui-examples.ts is stale or the registry incomplete (`npm run lint`). */

import { copyFileSync, existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "..");
const pkgDir = path.join(root, "node_modules", "@krizaka", "ui");
const registryDir = path.join(pkgDir, "registry");
const enrichDir = path.join(root, "content", "docs", "ui", "components");
const examplesFile = path.join(root, "lib", "ui-examples.ts");
const shotsDir = path.join(root, "public", "ui-examples");
const check = process.argv.includes("--check");
const strict = check || process.argv.includes("--strict");

const index = JSON.parse(readFileSync(path.join(registryDir, "index.json"), "utf8"));
const items = index.items.map((entry) => JSON.parse(readFileSync(path.join(registryDir, `${entry.name}.json`), "utf8")));
const names = new Set(items.map((item) => item.name));
const problems = [];

for (const item of items) {
  const where = `@krizaka/ui/registry/${item.name}`;
  if (!item.title || !item.summary) problems.push(`${where}: no title or summary (meta.ts)`);
  if (!["web", "native", "both"].includes(item.platforms)) problems.push(`${where}: unknown platforms "${item.platforms}"`);
  if (!item.whenToUse?.length || !item.accessibility) problems.push(`${where}: no "when to use" or accessibility (meta.ts)`);
  for (const side of ["web", "native"]) {
    const expected = item.platforms === "both" || item.platforms === side;
    if (expected && !item[side]?.examples?.length) problems.push(`${where}: no ${side} example`);
    for (const example of item[side]?.examples ?? []) {
      const compiled = path.join(registryDir, `${example.path.replace(/\.tsx$/, "")}.js`);
      if (side === "web" && !existsSync(compiled)) problems.push(`${where}: ${example.path} is not compiled in the package`);
      if (!example.code) problems.push(`${where}: ${example.path} has no code`);
    }
  }
  for (const related of [...(item.related ?? []), ...(item.whenNotToUse ?? []).map((w) => w.use).filter(Boolean)]) {
    if (!names.has(related)) problems.push(`${where}: unknown related component "${related}"`);
  }
}
for (const file of existsSync(enrichDir) ? readdirSync(enrichDir) : []) {
  if (file.endsWith(".mdx") && !names.has(file.replace(/\.mdx$/, ""))) {
    problems.push(`content/docs/ui/components/${file}: no component of that name in the registry (an enrichment page needs one)`);
  }
}

const key = (example) => example.module.replace("@krizaka/ui/registry/examples/", "");
const webExamples = items.flatMap((item) => item.web?.examples ?? []);
const expected = `/* GENERATED by scripts/gen-ui-docs.mjs from @krizaka/ui@${index.version}/registry — do not edit (git-ignored).
   The live web examples of /docs/ui (client modules of the package), loaded by ExamplePreview. */

export const UI_EXAMPLES = {
${webExamples.map((example) => `  "${key(example)}": () => import("${example.module}"),`).join("\n")}
} as const;

export type UiExampleKey = keyof typeof UI_EXAMPLES;

export const UI_REGISTRY_VERSION = "${index.version}";
`;

const current = existsSync(examplesFile) ? readFileSync(examplesFile, "utf8") : "";
if (current !== expected) {
  if (check) problems.push("lib/ui-examples.ts is stale — run `npm run docs:ui` (or `npm install`).");
  else {
    writeFileSync(examplesFile, expected);
    console.log(`gen-ui-docs: lib/ui-examples.ts — ${webExamples.length} examples of ${items.length} components (@krizaka/ui@${index.version})`);
  }
}

// The screenshots of the native examples, served next to the pages: public/ui-examples/<name>/native/<example>.<theme>.png.
const shots = items.flatMap((item) => (item.native?.examples ?? []).flatMap((example) => Object.values(example.screenshots ?? {})));
for (const shot of shots) {
  if (!existsSync(path.join(registryDir, shot))) problems.push(`@krizaka/ui/registry/${shot}: missing screenshot`);
}
if (!check) {
  rmSync(shotsDir, { recursive: true, force: true });
  for (const shot of shots) {
    const from = path.join(registryDir, shot);
    if (!existsSync(from)) continue;
    const to = path.join(shotsDir, shot.replace(/^examples\//, ""));
    mkdirSync(path.dirname(to), { recursive: true });
    copyFileSync(from, to);
  }
}

for (const problem of problems) console.error(`gen-ui-docs: ${problem}`);
process.exit(strict && problems.length ? 1 : 0);
