#!/usr/bin/env node
/* Generates the /docs/ui component pages from the @krizaka/ui registry (installed package).

   - lib/ui-demos.ts                         ALWAYS rewritten: the import map of the live demos (one per primitive).
   - content/docs/ui/components/<name>.mdx   written ONLY when missing: a scaffold (front matter, live preview,
                                             import, props, Storybook story) that is then enriched by hand —
                                             an existing page is never overwritten.

   The Storybook story of each page is the first story titled `Primitives/<Name>` in the published Storybook
   index (NEXT_PUBLIC_STORYBOOK_URL); offline, or when none matches, the page has no story.

   Usage: node scripts/gen-ui-docs.mjs [--check]
     --check   writes nothing; exits 1 when a primitive has no page or lib/ui-demos.ts is stale (CI). */

import { existsSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "..");
const registryDir = path.join(root, "node_modules", "@krizaka", "ui", "registry");
const pagesDir = path.join(root, "content", "docs", "ui", "components");
const demosFile = path.join(root, "lib", "ui-demos.ts");
const check = process.argv.includes("--check");
const storybookUrl = (process.env.NEXT_PUBLIC_STORYBOOK_URL || "https://krizaka.github.io/krizaka-ui/latest").replace(/\/$/, "");

const index = JSON.parse(readFileSync(path.join(registryDir, "index.json"), "utf8"));
const items = index.items.map((entry) => JSON.parse(readFileSync(path.join(registryDir, `${entry.name}.json`), "utf8")));

const pascal = (name) => name.split("-").map((w) => w[0].toUpperCase() + w.slice(1)).join("");

async function storyIds() {
  if (check) return new Map();
  try {
    const res = await fetch(`${storybookUrl}/index.json`, { signal: AbortSignal.timeout(10_000) });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const { entries } = await res.json();
    const first = new Map();
    for (const [id, entry] of Object.entries(entries)) {
      if (entry.type === "story" && !first.has(entry.title)) first.set(entry.title, id);
    }
    return first;
  } catch (error) {
    console.warn(`gen-ui-docs: Storybook index unavailable (${error.message}) — pages are written without a story.`);
    return new Map();
  }
}

function demosModule() {
  const lines = items.map((item) => `  "${item.name}": () => import("@krizaka/ui/registry/demos/${item.name}"),`);
  return `/* GENERATED by scripts/gen-ui-docs.mjs from @krizaka/ui@${index.version}/registry — do not edit.
   One live demo per primitive (client modules of the package), loaded by ComponentPreview. */

export const UI_DEMOS = {
${lines.join("\n")}
} as const;

export type UiDemoName = keyof typeof UI_DEMOS;

export const UI_REGISTRY_VERSION = "${index.version}";
`;
}

function scaffold(item, story) {
  const imports = (item.demo?.content ?? "")
    .split("\n")
    .filter((line) => line.includes(`from "@krizaka/ui/${item.name}"`));
  const description = item.description.replace(/\s*(Server-safe|Client \("use client"\))\.?$/, "").replace(/\.$/, "");
  return `---
title: ${pascal(item.name)}
description: ${JSON.stringify(description)}
---

{/* Scaffolded by scripts/gen-ui-docs.mjs from @krizaka/ui/registry/${item.name} — enrich freely: it is never overwritten.
    Title and description shown on the site: messages → docs.pages.ui.${item.name}. */}

<ComponentPreview name="${item.name}" />

## Import

\`\`\`tsx
${imports.join("\n") || `import {} from "@krizaka/ui/${item.name}";`}
\`\`\`

## Props

<PropsTable of="${item.name}" />
${story ? `\n## In Storybook\n\n<StoryFrame story="${story}" />\n` : ""}`;
}

const stories = await storyIds();
let failures = 0;

const expected = demosModule();
const current = existsSync(demosFile) ? readFileSync(demosFile, "utf8") : "";
if (current !== expected) {
  if (check) {
    console.error("gen-ui-docs: lib/ui-demos.ts is stale — run `npm run docs:ui`.");
    failures++;
  } else {
    writeFileSync(demosFile, expected);
    console.log("gen-ui-docs: lib/ui-demos.ts written");
  }
}

mkdirSync(pagesDir, { recursive: true });
for (const item of items) {
  const page = path.join(pagesDir, `${item.name}.mdx`);
  if (existsSync(page)) continue;
  if (check) {
    console.error(`gen-ui-docs: ${item.name} has no page — run \`npm run docs:ui\`.`);
    failures++;
    continue;
  }
  writeFileSync(page, scaffold(item, stories.get(`Primitives/${pascal(item.name)}`)));
  console.log(`gen-ui-docs: content/docs/ui/components/${item.name}.mdx scaffolded`);
}

process.exit(failures ? 1 : 0);
